application: realtimeplayground
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /images
  static_dir: images
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always
  
- url: /
  static_files: templates/index.html
  upload: templates/index.html
  secure: always

- url: /sandbar
  static_files: templates/fake_devsite_sandbar.html
  upload: templates/fake_devsite_sandbar.html
  secure: always

- url: .*
  script: redirect.app
  secure: always

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Build files that have no effect in App Engine's runtime.
- ^.*\.MF$
- ^.*\.CMF$
- ^.*\.so$
- ^.*pywrap.+\.py$
- ^.*\.jslib$